// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package utils

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3187a61bDecodeGithubComSimpleMusicGatewayUtils(in *jlexer.Lexer, out *serviceCredentials) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "serviceId":
			out.ServiceID = string(in.String())
		case "servicePassword":
			out.ServicePassword = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3187a61bEncodeGithubComSimpleMusicGatewayUtils(out *jwriter.Writer, in serviceCredentials) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"serviceId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ServiceID))
	}
	{
		const prefix string = ",\"servicePassword\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ServicePassword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v serviceCredentials) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3187a61bEncodeGithubComSimpleMusicGatewayUtils(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v serviceCredentials) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3187a61bEncodeGithubComSimpleMusicGatewayUtils(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *serviceCredentials) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3187a61bDecodeGithubComSimpleMusicGatewayUtils(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *serviceCredentials) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3187a61bDecodeGithubComSimpleMusicGatewayUtils(l, v)
}
func easyjson3187a61bDecodeGithubComSimpleMusicGatewayUtils1(in *jlexer.Lexer, out *serviceAuthToken) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "authToken":
			out.AuthToken = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3187a61bEncodeGithubComSimpleMusicGatewayUtils1(out *jwriter.Writer, in serviceAuthToken) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"authToken\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AuthToken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v serviceAuthToken) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3187a61bEncodeGithubComSimpleMusicGatewayUtils1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v serviceAuthToken) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3187a61bEncodeGithubComSimpleMusicGatewayUtils1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *serviceAuthToken) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3187a61bDecodeGithubComSimpleMusicGatewayUtils1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *serviceAuthToken) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3187a61bDecodeGithubComSimpleMusicGatewayUtils1(l, v)
}
