// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson844dad31DecodeGithubComSimpleMusicGatewayModels(in *jlexer.Lexer, out *AuthCode) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "authCode":
			out.AuthCode = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson844dad31EncodeGithubComSimpleMusicGatewayModels(out *jwriter.Writer, in AuthCode) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"authCode\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AuthCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthCode) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson844dad31EncodeGithubComSimpleMusicGatewayModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthCode) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson844dad31EncodeGithubComSimpleMusicGatewayModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthCode) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson844dad31DecodeGithubComSimpleMusicGatewayModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthCode) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson844dad31DecodeGithubComSimpleMusicGatewayModels(l, v)
}
